Repository goreleaser/goreleaser-action, pull requests merged in 2020-11, with the labels that each got.

#252 Add install-only option for using goreleaser in user scripts
  README.md
  action.yml
  dist/index.js
  src/main.ts
Labels: size/M

#258 Container based developer flow
  .dockerignore
  .github/workflows/pre-checkin.yml
  .github/workflows/test.yml
  Dockerfile.dev
  README.md
  docker-bake.hcl
Labels: size/L

#257 Upload artifact example
  .github/workflows/ci.yml
  README.md
  go.mod
Labels: size/M

#259 Set GORELEASER_CURRENT_TAG
  dist/index.js
  src/main.ts
Labels: size/XS
