Repository goreleaser/goreleaser-action, pull requests merged in 2021-05, with the labels that each got.

#282 fix(ci): pin actions to major
  .github/workflows/ci.yml
  .github/workflows/test.yml
Labels: size/S

#284 feat: support downloading goreleaser pro
  README.md
  __tests__/github.test.ts
  __tests__/installer.test.ts
  __tests__/pro.test.ts
  dist/index.js
  src/github.ts
  src/installer.ts
  src/main.ts
  src/pro.ts
Labels: size/L

#285 docs: remove changelog
  CHANGELOG.md
Labels: size/L

#288 test: ci tests pro version
  .github/workflows/ci.yml
Labels: enhancement, size/S
