Repository goreleaser/goreleaser-action, pull requests merged in 2022-12, with the labels that each got.

#370 fix: do not override GORELEASER_CURRENT_TAG
  dist/index.js
  dist/index.js.map
  src/main.ts
Labels: size/XS

#382 feat!: remove auto-snapshot on dirty tag
  .github/workflows/ci.yml
  __tests__/git.test.ts
  dist/index.js
  dist/index.js.map
  src/git.ts
  src/main.ts
Labels: enhancement, size/L

#366 docs: add example when using workdir along with upload-artifact
  README.md
Labels: size/XS

#384 Update Readme to reference `goreleaser/goreleaser-action@v4`
  README.md
Labels: size/S

#386 docs: fix README badge
  README.md
Labels: size/XS
